/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface QvFontface {}
  interface QvPillContainer {
    'list': any[];
  }
  interface QvPillTest {}
  interface TableGrid {}
  interface TableRow {
    'canRender': boolean;
    'columns'?: any;
    'observer': any;
    'row'?: any;
  }
  interface VGrid {}
  interface VRow {
    'columns'?: any;
    'row'?: any;
  }
}

declare global {


  interface HTMLQvFontfaceElement extends Components.QvFontface, HTMLStencilElement {}
  var HTMLQvFontfaceElement: {
    prototype: HTMLQvFontfaceElement;
    new (): HTMLQvFontfaceElement;
  };

  interface HTMLQvPillContainerElement extends Components.QvPillContainer, HTMLStencilElement {}
  var HTMLQvPillContainerElement: {
    prototype: HTMLQvPillContainerElement;
    new (): HTMLQvPillContainerElement;
  };

  interface HTMLQvPillTestElement extends Components.QvPillTest, HTMLStencilElement {}
  var HTMLQvPillTestElement: {
    prototype: HTMLQvPillTestElement;
    new (): HTMLQvPillTestElement;
  };

  interface HTMLTableGridElement extends Components.TableGrid, HTMLStencilElement {}
  var HTMLTableGridElement: {
    prototype: HTMLTableGridElement;
    new (): HTMLTableGridElement;
  };

  interface HTMLTableRowElement extends Components.TableRow, HTMLStencilElement {}
  var HTMLTableRowElement: {
    prototype: HTMLTableRowElement;
    new (): HTMLTableRowElement;
  };

  interface HTMLVGridElement extends Components.VGrid, HTMLStencilElement {}
  var HTMLVGridElement: {
    prototype: HTMLVGridElement;
    new (): HTMLVGridElement;
  };

  interface HTMLVRowElement extends Components.VRow, HTMLStencilElement {}
  var HTMLVRowElement: {
    prototype: HTMLVRowElement;
    new (): HTMLVRowElement;
  };
  interface HTMLElementTagNameMap {
    'qv-fontface': HTMLQvFontfaceElement;
    'qv-pill-container': HTMLQvPillContainerElement;
    'qv-pill-test': HTMLQvPillTestElement;
    'table-grid': HTMLTableGridElement;
    'table-row': HTMLTableRowElement;
    'v-grid': HTMLVGridElement;
    'v-row': HTMLVRowElement;
  }
}

declare namespace LocalJSX {
  interface QvFontface {}
  interface QvPillContainer {
    'list'?: any[];
  }
  interface QvPillTest {}
  interface TableGrid {}
  interface TableRow {
    'canRender'?: boolean;
    'columns'?: any;
    'observer'?: any;
    'row'?: any;
  }
  interface VGrid {}
  interface VRow {
    'columns'?: any;
    'row'?: any;
  }

  interface IntrinsicElements {
    'qv-fontface': QvFontface;
    'qv-pill-container': QvPillContainer;
    'qv-pill-test': QvPillTest;
    'table-grid': TableGrid;
    'table-row': TableRow;
    'v-grid': VGrid;
    'v-row': VRow;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'qv-fontface': LocalJSX.QvFontface & JSXBase.HTMLAttributes<HTMLQvFontfaceElement>;
      'qv-pill-container': LocalJSX.QvPillContainer & JSXBase.HTMLAttributes<HTMLQvPillContainerElement>;
      'qv-pill-test': LocalJSX.QvPillTest & JSXBase.HTMLAttributes<HTMLQvPillTestElement>;
      'table-grid': LocalJSX.TableGrid & JSXBase.HTMLAttributes<HTMLTableGridElement>;
      'table-row': LocalJSX.TableRow & JSXBase.HTMLAttributes<HTMLTableRowElement>;
      'v-grid': LocalJSX.VGrid & JSXBase.HTMLAttributes<HTMLVGridElement>;
      'v-row': LocalJSX.VRow & JSXBase.HTMLAttributes<HTMLVRowElement>;
    }
  }
}


